### ISSUE TITLE
Override the ctrl+s keybinding if the file requires root privileges

### ISSUE THREAD

**Issue by yy0931** [yy0931/save-as-root#10]
It's tedious to type the command every time.

TODO: Check the file permission (`fs.accessSync(file, fs.constants.W_OK)`) on onChangeActiveEditor and enable/disable the keybinding with vscode.commands.executeCommand('setContext' ,...)

**Comment by wolfewa** [comment]
I just added a key binding for it.  I don't generally use Alt+s, so I just use Ctrl +s for a normal save and Alt+s for Save as Root.

File->Preferences -> Keyboard Shortcuts or Ctrl+k Ctrl+s or the little gear next to the command
<img width="470" alt="image" src="https://user-images.githubusercontent.com/32490481/187100578-3e3ccda9-5ea0-4c80-9a04-bdcdcc35e1e1.png">
