### ISSUE TITLE
sudo: option '--preserve-env' doesn't allow an argument

### ISSUE THREAD

**Issue by Tenri1999** [yy0931/save-as-root#2]
![image](https://user-images.githubusercontent.com/3979239/130442573-b9f2b755-bb3c-4014-a5c0-b48bc08628b2.png)

I get this error when attempting to run the command. Looking up the error itself doesn't seem to turn up with anything...

**Comment by yy0931** [comment]
@Tenri1999 Thank you for reporting the bug. I fixed it in https://github.com/yy0931/save-as-root/commit/6dc3514ac12eb243d81372790f66f3ca935c8caf and published v1.3.6. Does it work in your environment?

**Comment by yy0931** [comment]
I got exactly the same error on Ubuntu16.04, which uses sudo 1.8.16, and confirmed that v1.3.6 of this extension fixed the problem. If you're still seeing errors, please reopen this issue.
