### ISSUE TITLE
[Feature Request] Save password on entry

### ISSUE THREAD

**Issue by modernben** [yy0931/save-as-root#4]
Every time I "Save as Root" it asks for the password. Can you have it remember it for this project?

**Comment by yy0931** [comment]
Thank you for reporting the problem. There was a problem with the way the sudo command was invoked. I've fixed it in https://github.com/yy0931/save-as-root/commit/de7f7fa6ce6ab7449c1f9c2d18d1514de0d8008b and published v1.3.9.

**Comment by modernben** [comment]
This is so much better now!!!!!
Thanks!

**Comment by francesco-loreti** [comment]
Thank you for your work! 
I wanted to point out that when I use the extension, it always asks me for my password every time I save. 
I insert it and it asks me for it every time I save one file. 

Is there a way to save it the first time I log in?
