### ISSUE TITLE
[Feature Request] Open as root

### ISSUE THREAD

**Issue by alainwolf** [yy0931/save-as-root#6]
Would it be possible to also open files (and browse directories) as root?

**Comment by yy0931** [comment]
Thank you for your request. But I have no plans to implement it.
Implementing it will require a lot of work and may introduce security issues because extensions will use the file contents with the user's privilege.

**Comment by yy0931** [comment]
FYI these links may help
https://github.com/microsoft/vscode/issues/48659#issuecomment-1030989764 (If your local machine is Linux)
https://github.com/microsoft/vscode/issues/48659#issuecomment-1019542982 (If your local machine is Windows)

**Comment by BigSethCode** [comment]
i wanted to use it on a remote linux ubuntu aws server and after installing it i couldn't connect to the server with ssh
but when I uninstalled it it was finally possible
