### ISSUE TITLE
password prompt closes on focus change

### ISSUE THREAD

**Issue by stonebeaver** [yy0931/save-as-root#9]
When the Remote - SSH extension prompts for a password, a text input bar appears on the north edge of the window. One may change to another window on the desktop, get the password, focus back to the vscode's window and paste the password.
When the Save as Root in Remote - SSH extension prompts for password, the text input bar appears on the north edge of the window. When I change to another window on the desktop, the input bar vanishes and the procedure is cancelled.
Would it be possible, to keep the password input bar open? This would provide for a more consistent user experience. For your considerations thanks in advance.

**Comment by MaykGyver** [comment]
Thank you!
